repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      exclude: (migrations|alembic.ini)
      args: [--profile, black, --line-length=120]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
    - id: flake8
      exclude: (migrations|alembic.ini)
      additional_dependencies:
        - flake8-docstrings

- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
    - id: black
      exclude: (migrations|alembic.ini)
      args: [--line-length=120]

- repo: https://github.com/python-poetry/poetry
  rev: 1.7.1
  hooks:
  - id: poetry-export
    args: ["--only", "main", "--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
  - id: poetry-export
    args: ["--only", "dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements_dev.txt"]
  - id: poetry-export
    args: ["--only", "test", "--without-hashes", "-f", "requirements.txt", "-o", "requirements_test.txt"]
