version: '3.8'

volumes:
  rabbitmq_data:
  celery_data:
  redis_data:
  postgres_data:

services:

  currency:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      -  ./:/code/
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15.4-alpine
    container_name: terexov-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    restart: always

  celery:
    restart: always
    container_name: terexov-celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.core.celery_config worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

  celery-beat:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A src.core.celery_config beat -l info
    volumes:
      - celery_data:/var/lib/celery/data
      - .:/code
    depends_on:
      - currency

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis.conf:/etc/keydb/redis.conf
      - redis_data:/data
