"""Add name field

Revision ID: bf7b2e016054
Revises: 9bcad76b6e42
Create Date: 2024-06-30 21:16:27.132753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf7b2e016054'
down_revision: Union[str, None] = '9bcad76b6e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'name')
    # ### end Alembic commands ###
